# Generated by Django 4.0.4 on 2022-06-09 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 13, 21, 45, 315044), verbose_name='date published'),
        ),
    ]
