# Generated by Django 4.1.3 on 2022-12-04 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
